<?php

namespace AppBundle\Repository;

/**
 * AnalyseMedicaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyseMedicaleRepository extends \Doctrine\ORM\EntityRepository
{
}
