<?php

namespace AppBundle\Repository;

/**
 * AntecedantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedantRepository extends \Doctrine\ORM\EntityRepository
{
}
