<?php

namespace AppBundle\Repository;

/**
 * CarteAbonneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteAbonneeRepository extends \Doctrine\ORM\EntityRepository
{
}
