<?php

namespace AppBundle\Repository;

/**
 * CreneauxMedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauxMedecinRepository extends \Doctrine\ORM\EntityRepository
{
}
