<?php

namespace AppBundle\Repository;

/**
 * FactureOrdonanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureOrdonanceRepository extends \Doctrine\ORM\EntityRepository
{
}
