<?php

namespace AppBundle\Repository;

/**
 * FactureAnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureAnalyseRepository extends \Doctrine\ORM\EntityRepository
{
}
