<?php

namespace AppBundle\Repository;

/**
 * ResultatAnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatAnalyseRepository extends \Doctrine\ORM\EntityRepository
{
}
