<?php
/**
 * Created by PhpStorm.
 * User: numtekdev2
 * Date: 11/26/18
 * Time: 10:11 AM
 */

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends EntityRepository
{
}