<?php

namespace AppBundle\Repository;

/**
 * TechnicienLaboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicienLaboRepository extends \Doctrine\ORM\EntityRepository
{
}
