<?php

namespace AppBundle\Repository;

/**
 * TypeConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeConsultationRepository extends \Doctrine\ORM\EntityRepository
{
}
